### ISSUE TITLE
Add a standard README

### ISSUE THREAD

**Issue by Rishabh04-02** [Teamexe/Quiz-Generator#1]
Here is a sample minimal standard readme which one can refer [sample](https://github.com/RichardLitt/standard-readme/blob/master/example-readmes/minimal-readme.md)
OR you can refer this [sample2](https://github.com/Rishabh04-02/Elective-manager/blob/master/README.md)

**Comment by Rishabh04-02** [comment]
@octacode This readme has been updated. Please modify the content as per the needs.

**Comment by octacode** [comment]
Thanks! The readme looks fine to me. Closing this issue for now. 👍
